# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

#PreCommit:
#  RuboCop:
#    enabled: true
#    on_warn: fail # Treat all warnings as failures
#
#  TrailingWhitespace:
#    enabled: true
#    exclude:
#      - '**/db/structure.sql' # Ignore trailing whitespace in generated files
#
#PostCheckout:
#  ALL: # Special hook name that customizes all hooks of this type
#    quiet: true # Change all post-checkout hooks to only display output on failure
#
#  IndexTags:
#    enabled: true # Generate a tags file with `ctags` each time HEAD changes

verify_signatures: false

# PostCommit:
#   CustomScript:
#     enabled: true
#     required_executable: grep
#     command: ['grep -E "^\[\#[0-9]{9}\]" .git/COMMIT_EDITMSG']

#   GitGuilt: disabled
#   GitLfs: disabled
#   IndexTags: disabled
#   SubmoduleStatus: disabled
# PostRewrite:
#   IndexTags: disabled
#   SubmoduleStatus: disabled
CommitMsg:
  CapitalizedSubject:
    enabled: true
  EmptyMessage:
    enabled: true
#   GerritChangeId: disabled
#   HardTabs: disabled
#   MessageFormat: disabled
#   RussianNovel: disabled
  SingleLineSubject:
    enabled: true
#   SpellCheck: disabled
  TextWidth:
    enabled: true
  TrailingPeriod:
    enabled: true
# PostMerge:
#   GitLfs: disabled
#   IndexTags: disabled
#   SubmoduleStatus: disabled
# PrePush:
#   GitLfs: disabled
#   Minitest: disabled
#   ProtectedBranches: disabled
#   TestUnit: disabled
# PostCheckout:
#   GitLfs: disabled
#   IndexTags: disabled
#   SubmoduleStatus: disabled
# PreRebase:
#   MergedCommits: disabled
PreCommit:
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  BrokenSymlinks:
    enabled: true
  CaseConflicts:
    enabled: true
#   ChamberCompare: disabled
#   ChamberSecurity: disabled
#   ChamberVerification: disabled
#   CodeSpellCheck: disabled
#   Credo: disabled
#   Dogma: disabled
#   ExecutePermissions: disabled
#   Fasterer: disabled
#   FixMe: disabled
#   FileSize: disabled
#   Flay: disabled
#   Foodcritic: disabled
#   ForbiddenBranches: disabled
#   GoLint: disabled
#   GoVet: disabled
#   Hadolint: disabled
#   HardTabs: disabled
#   Hlint: disabled
#   ImageOptim: disabled
#   KtLint: disabled
#   LicenseFinder: disabled
#   LicenseHeader: disabled
#   Mdl: disabled
  MergeConflicts:
    enabled: true
#   Pronto: disabled
#   RuboCop: disabled
#   SemiStandard: disabled
#   ShellCheck: disabled
#   SlimLint: disabled
#   Sqlint: disabled
#   Standard: disabled
#   Stylelint: disabled
#   TrailingWhitespace: disabled
#   TravisLint: disabled
#   Vint: disabled
#   LineEndings: disabled
#   XmlLint: disabled
#   XmlSyntax: disabled
#   YamlLint: disabled
#   YamlSyntax: disabled
#   YardCoverage: disabled
#   YarnCheck: disabled
PrepareCommitMsg:
  CustomScript:
    enabled: true
    required_executable: 'git-duet-prepare-commit-msg'
#   ReplaceBranch: disabled
