language: go
go:
  - 1.12.x
go_import_path: code.cloudfoundry.org/cli
install:
- go get -u github.com/onsi/ginkgo/ginkgo
script:
- go vet -all  ./api/... ./actor/... ./command ./integration/... ./types ./util ./version
- NODES=1 make units-full
branches:
  only:
  - master
  - travis
os:
  - linux
